[
  {
    title: 'Landslide warning as heavy rain expected across the country.',
    type: 'newsStory',
    tag: 'News',
    val: 0,
    published: '2023-05-09T03:00:00Z',
    link: 'https://www.geonet.org.nz/news/7iXw4yBatVAbBP0rkcpr5l',
    mlink: 'https://www.geonet.org.nz/news/7iXw4yBatVAbBP0rkcpr5l',
  },
  {
    title:
      'Checking in on our active Kāpiti and Manawatū slow slip earthquakes ',
    type: 'newsStory',
    tag: 'News',
    val: 0,
    published: '2023-05-05T02:40:00Z',
    link: 'https://www.geonet.org.nz/news/6vAA6FVHI9ojGmkONfsoOi',
    mlink: 'https://www.geonet.org.nz/news/6vAA6FVHI9ojGmkONfsoOi',
  },
  {
    title:
      'Te Wai ā-moe (Crater Lake) is cooling, volcanic unrest remains low for Mt Ruapehu. The Volcanic Alert Level remains at Level 1.  ',
    type: 'vab',
    tag: 'Volcanic Activity Bulletin',
    val: 1,
    published: '2023-05-02T22:00:00Z',
    link: 'https://www.geonet.org.nz/vabs/1S1ZT4HHjfPYXZHdK6affE',
    mlink: 'https://www.geonet.org.nz/vabs/1S1ZT4HHjfPYXZHdK6affE',
  },
  {
    title: 'How Often Do You Collect Data?',
    type: 'dataBlog',
    tag: 'Data Blog',
    val: 0,
    published: '2023-05-02T01:30:00Z',
    link: 'https://www.geonet.org.nz/news/4ydBp8LLj0PrRCYyieinVJ',
    mlink: 'https://www.geonet.org.nz/news/4ydBp8LLj0PrRCYyieinVJ',
  },
  {
    title: 'How does the Kawerau earthquake swarm compare with other swarms?',
    type: 'dataBlog',
    tag: 'Data Blog',
    val: 0,
    published: '2023-04-05T22:30:00Z',
    link: 'https://www.geonet.org.nz/news/4JzNrNwt67etzd8oPMdI8S',
    mlink: 'https://www.geonet.org.nz/news/4JzNrNwt67etzd8oPMdI8S',
  },
  {
    title:
      'Taupō Volcano remains in minor unrest despite earthquake activity having almost returned to normal. Volcanic Alert Level remains at Level 1. ',
    type: 'vab',
    tag: 'Volcanic Activity Bulletin',
    val: 1,
    published: '2023-04-05T02:00:00Z',
    link: 'https://www.geonet.org.nz/vabs/1NuSQzVcrYLx4cT4hleSqR',
    mlink: 'https://www.geonet.org.nz/vabs/1NuSQzVcrYLx4cT4hleSqR',
  },
  {
    title: 'Kawerau Earthquake Swarm',
    type: 'newsStory',
    tag: 'News',
    val: 0,
    published: '2023-03-19T00:37:00Z',
    link: 'https://www.geonet.org.nz/news/4PuHMfEQzaMgI9Hudgf8dp',
    mlink: 'https://www.geonet.org.nz/news/4PuHMfEQzaMgI9Hudgf8dp',
  },
  {
    title:
      'Whakaari/White Island continues to emit significant amounts of gas and steam. Volcanic Alert Level remains at Level 2. ',
    type: 'vab',
    tag: 'Volcanic Activity Bulletin',
    val: 2,
    published: '2023-03-10T03:00:00Z',
    link: 'https://www.geonet.org.nz/vabs/3SPTgWFGn89o5XxeLB3YJ1',
    mlink: 'https://www.geonet.org.nz/vabs/3SPTgWFGn89o5XxeLB3YJ1',
  },
  {
    title: 'Does GeoNet delete earthquakes?',
    type: 'newsStory',
    tag: 'News',
    val: 0,
    published: '2023-03-08T20:30:00Z',
    link: 'https://www.geonet.org.nz/news/5mOVt0syTsdjEFYx9uLch6',
    mlink: 'https://www.geonet.org.nz/news/5mOVt0syTsdjEFYx9uLch6',
  },
  {
    title:
      'Minor unrest continues at Taupō Volcano including a recent M4.4  earthquake. Volcanic Alert Level remains at Level 1.',
    type: 'vab',
    tag: 'Volcanic Activity Bulletin',
    val: 1,
    published: '2023-03-06T21:30:00Z',
    link: 'https://www.geonet.org.nz/vabs/5c0mzV2kbLF6ZOueLkWcGQ',
    mlink: 'https://www.geonet.org.nz/vabs/5c0mzV2kbLF6ZOueLkWcGQ',
  },
];
